### ISSUE TITLE
The client can't build.

### ISSUE THREAD

**Issue by zisis912** [Mixaz017/idkr#11]
after installing the dependencies, i ran npm run dist, but at the end of the compiling proccess there was an error. Here are the logs.
```0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'dist'
1 verbose cli ]
2 info using npm@6.14.8
3 info using node@v14.15.1
4 verbose run-script [ 'predist', 'dist', 'postdist' ]
5 info lifecycle idkr@1.0.8~predist: idkr@1.0.8
6 info lifecycle idkr@1.0.8~dist: idkr@1.0.8
7 verbose lifecycle idkr@1.0.8~dist: unsafe-perm in lifecycle true
8 verbose lifecycle idkr@1.0.8~dist: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\anast\Documents\ΖΗΣΗΣ\custom krunker client\idkr-master\node_modules\.bin;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files\nodejs\;C:\Program Files\Git\cmd;C:\Gradle\gradle-6.7.1\bin;C:\Users\anast\AppData\Local\Programs\Python\Python39\Scripts\;C:\Users\anast\AppData\Local\Programs\Python\Python39\;C:\Users\anast\AppData\Local\Microsoft\WindowsApps;C:\Users\anast\AppData\Roaming\npm;C:\Users\anast\AppData\Local\Programs\Microsoft VS Code\bin;C:\Users\anast\AppData\Local\GitHubDesktop\bin
9 verbose lifecycle idkr@1.0.8~dist: CWD: C:\Users\anast\Documents\ΖΗΣΗΣ\custom krunker client\idkr-master
10 silly lifecycle idkr@1.0.8~dist: Args: [ '/d /s /c', 'electron-builder' ]
11 silly lifecycle idkr@1.0.8~dist: Returned: code: 1  signal: null
12 info lifecycle idkr@1.0.8~dist: Failed to exec dist script
13 verbose stack Error: idkr@1.0.8 dist: `electron-builder`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:315:20)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:315:20)
13 verbose stack     at maybeClose (internal/child_process.js:1048:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
14 verbose pkgid idkr@1.0.8
15 verbose cwd C:\Users\anast\Documents\ΖΗΣΗΣ\custom krunker client\idkr-master
16 verbose Windows_NT 10.0.19042
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "dist"
18 verbose node v14.15.1
19 verbose npm  v6.14.8
20 error code ELIFECYCLE
21 error errno 1
22 error idkr@1.0.8 dist: `electron-builder`
22 error Exit status 1
23 error Failed at the idkr@1.0.8 dist script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by Mixaz017** [comment]
It's confirmed to work on Node v12, can you try again on that version?
If it still fails, it might be because of special characters in your folder path (potentially including space characters) so it's worth a try to remove special characters if Node downgrade doesn't work.

**Comment by Mixaz017** [comment]
Seems to be special character issue. I tried to build on Node v12.19.0, with special characters, and it failed to build. I removed special characters and now it can build successfully. Its not affected by spaces

**Comment by zisis912** [comment]
ok, I will try somewhere else (btw those are greek characters, not random unicode)

**Comment by zisis912** [comment]
I tried without the special characters. It built successfully, but when i launched it, apart from the custom launch screen all the CSS was default. I think there is supposed to be a custom css there?

**Comment by zisis912** [comment]
it built successfully, but i want to ask a question. If you update the repo, do I have to install the client again or it autoupdates? Also, does the same happen with krunker updates?

**Comment by Mixaz017** [comment]
It automatically updates when there's a new release. Client updates are not related to Krunker updates.

**Comment by zisis912** [comment]
I know that krunker auto-updates when there's a new release, but does your client also update?

**Comment by Mixaz017** [comment]
Oh I meant client auto updates. My bad. And yes it does.

**Comment by zisis912** [comment]
@Mixaz017 also, is there a way to intergrate custom css in the client and build it with the custom css? Like, not put stuff in the swap folder, but have the exe file already have the custom css in it

**Comment by Mixaz017** [comment]
Of course you can do anything you want by modifying the code but you will lose it on auto update. You can disable auto update but this way you no longer receive updates from future releases

**Comment by zisis912** [comment]
if it is relatively easy to intergrate custom css into the client could you tell me how its done right now?

**Comment by zisis912** [comment]
@Mixaz017

**Comment by Mixaz017** [comment]
MTZ is not open source

**Comment by zisis912** [comment]
@Mixaz017 ok, but as I asked if it is easy to intergrate custom css into a client could you tell how to do it?

**Comment by Mixaz017** [comment]
You just have to append `style` or `link` tag

**Comment by zisis912** [comment]
i dont know too much about coding, if it is a few lines of code then import the assets could you show an example of code

**Comment by Mixaz017** [comment]
It's really just `createElement()` and `appendChild()`. I'm not going to provide further support for questions you can find an answer online easily.

**Comment by zisis912** [comment]
i could definitely find answers about children and appending online, but there are no videos about how to code a krunker client. If you know of any vid that helps with this tell me

**Comment by Mixaz017** [comment]
I don't know and don't care about video tutorial stuff. Also I only provide support for idkr client itself, not for other clients or making a client.
