### ISSUE TITLE
Mouse not locking

### ISSUE THREAD

**Issue by ItsElectra** [Mixaz017/idkr#14]
the mouse isn't locking, so when i turn and my mouse would touch the edge of the screen, it snaps my aim. this game is a shooter, so this is a problem.

https://user-images.githubusercontent.com/59057998/105865235-b631ab00-5fc0-11eb-9926-48333c647029.mp4

EDIT: nvm im a moron it just snaps fix that tho plz thanks

**Comment by ColdMoonNight** [comment]
What really is the issue that you are having? Once it touches the edge, does it snap to the middle?

**Comment by Mixaz017** [comment]
It's hard to see the issue since the video's FPS is too low but at least the mouse is being locked. I don't think this is a client specific issue, try other browsers/clients or decrease polling rate of your mouse.
