### ISSUE TITLE
Pressing "ESC" to bring up the main menu causes the game to freeze.

### ISSUE THREAD

**Issue by DUBTF2** [Mixaz017/idkr#2]
About a couple of minutes while using this client, pressing "ESC" to bring up the main menu causes the game to freeze unless you alt tab back in, this also happens after a round is over when the leader board shows up. P.S. I really love this client, and I can't wait for more updates in the future! :)

**Comment by philzgoodman** [comment]
I've encountered the same issue, but noticed that it worked better when I was using the "Default" graphics settings rather than "Open GL"

**Comment by Mixaz017** [comment]
I need more information about this from others... as I cant reproduce the problem and seems like it happens randomly

**Comment by DUBTF2** [comment]
> 
> 
> I've encountered the same issue, but noticed that it worked better when I was using the "Default" graphics settings rather than "Open GL"

I fixed the issue, it was my custom css that had this blur effect in the main menu It was enough to freeze my game and drop my fps down to 150. I've fixed it and my fps went to 600 in the main menu and no longer freeze's, it wasn't the client since it freeze on three different clients I've tried (brave, custom client, official).

**Comment by Mixaz017** [comment]
> I've encountered the same issue, but noticed that it worked better when I was using the "Default" graphics settings rather than "Open GL"

Switching to OpenGL seems to be the solution for now. Looking for an actual fix...
