### ISSUE TITLE
idkr not running on lutris and the terminal

### ISSUE THREAD

**Issue by stationaryStation** [Mixaz017/idkr#21]
![Screenshot from 2021-04-29 11-17-44](https://user-images.githubusercontent.com/81704775/116575446-a5a11180-a8dc-11eb-8a97-489da2427c33.png)
Maybe XInitThreads is not working for me or something. I tried running without arguments the appimage and from Lutris. Is there a solution to this?

Also i am using ubuntu 20.10

**Comment by giantninja908** [comment]
this error has to do with you changing the setting "in process gpu"
open ~/.config/idkr/config.json and change "inProcessGpu" from true to false

this is an electron flag issue, not idkr

**Comment by mty22** [comment]
@giantninja908 can you link to the respective issue here? https://github.com/electron/electron/issues

core dumps on Fedora 33:
```
(py38)  L [Sun May 02 22:53:22 matt@fc-box.local ~]$ ./idkr-portable-linux-x86_64.AppImage
22:53:36.836 › idkr@1.2.2 { Electron: 9.4.4, Node: 12.14.1, Chromium: 83.0.4103.122 }
[xcb] Unknown request in queue while dequeuing
[xcb] Most likely this is a multi-threaded client and XInitThreads has not been called
[xcb] Aborting, sorry about that.
idkr: xcb_io.c:163: dequeue_pending_request: Assertion `!xcb_xlib_unknown_req_in_deq' failed.
Aborted (core dumped)
```

5.11.16-200.fc33.x86_64

nvidia drivers 465.24.02

**Comment by NullDev** [comment]
Yes this is a chromium bug when using In-proccess-gpu on Linux:

![unknown-24](https://user-images.githubusercontent.com/22935000/116814546-d5a91880-ab59-11eb-9a5e-0cb7567357c4.png)

**Comment by stationaryStation** [comment]
Yea, by reinstalling pop 20.10 it fixed the problem. But I am going to leave the devs if they want to close this issue.
