### ISSUE TITLE
console is being spammed on latest master

### ISSUE THREAD

**Issue by KraXen72** [Mixaz017/idkr#33]
there are 10 console warns every second which slows down the client a lot on latest master.
![image](https://user-images.githubusercontent.com/21956756/126708494-327fddbb-9b46-4261-a18a-4a262a8c0f14.png)

i temporarily fixed it by adding ``console.warn = () => {}`` but that's not a real solution. please fix the source of this warn. thanks

**Comment by NullDev** [comment]
The "source" of this warning is in Krunkers code. Not much we can do about it except hiding it or nulling out the caller.

**Comment by KraXen72** [comment]
oh, interesting. i know that krunker disabled console logging (which is not a particualrly nice thing to do), and i didn't think reenabling was possible but here we are? anyway thank you for clarifying. i'd just suggest binding the old console to some custom object that only idkr uses so krunker doesen't have the console but idkr does

**Comment by Mixaz017** [comment]
What. Krunker logs are as important as idkr logs.
