### ISSUE TITLE
why use jsdoc typedefs and not typescript?

### ISSUE THREAD

**Issue by KraXen72** [Mixaz017/idkr#37]
why would you guys use jsdoc typedefs and type functionality over typescript? typescript seems like less work..

**Comment by NullDev** [comment]
Overall, TypeScript is more work. 
Considering we need a total re-write, build chains, have build times, probably get a lot of whacky errors, have a lot of resulting build overhead, etc. With JSDoc we take TypeScripts Type safety without having to worry about all the other problems that come with it

**Comment by Mixaz017** [comment]
I'm not a TS expert but TS doesn't work very well with remote contents imo. Since you don't have control over variables from remote contents, you must assume `any` type for all variables that can potentially be any type (which includes the whole `window`).

**Comment by KraXen72** [comment]
alright then
