### ISSUE TITLE
menu timer toggle & settings made by userscripts don't work

### ISSUE THREAD

**Issue by KraXen72** [Mixaz017/idkr#38]
show menu timer toggle doesen't work, also any toggle made by userscripts.
idk if these are 2 separate issues, but the toggle doesen't even remember its state, and doesen't turn off anything,

for the settings made with userscripts (v1.0), they do save, but the modified value is not read on start, so e.g. i turn the toggle off, userscirpt reads it as off, so does what its supposed to, but when i go to settings, the toggle is on.

for the menu timer, i couldn't control it in any way by the toggle, only thing that helped was doing this change:
```diff
--- a/app/modules/styles-injection.js
+++ b/app/modules/styles-injection.js
@@ -80,6 +80,5 @@ const menuTimerStyles = `
 `;

 module.exports = {
-       baseStyles,
-       menuTimerStyles
+       baseStyles
 };
 ```

**Comment by Mixaz017** [comment]
Fixed by 805113a, closing
