### ISSUE TITLE
Freezing after death

### ISSUE THREAD

**Issue by pythonicBoi** [Mixaz017/idkr#6]
If you click more then once upon death (to get back in-game), you freeze till you resize the screen, though you've already spawned. Otherwise, the best client ever.

**Comment by 0x506978656c** [comment]
This is general krunker issue and is not related to the client sadly.
If u wish to get this fixed contact devs pls

Mixaz close if nb

**Comment by Mixaz017** [comment]
Pretty sure its related to Electron, not sure if I want to downgrade electron and close the issue though.

**Comment by 0x506978656c** [comment]
Many have had issues with browser so it’s not entirely electron but keep open and I’ll investigate further

**Comment by Mixaz017** [comment]
Oh I meant like its probably Chromium issue used in Electron, my bad

**Comment by NLDev** [comment]
Seems like they fixed it. Haven't experienced that in a while. 
Used to have this problem on the Official Client and Custom Client as well, so not related to Idkr. 
But as I said, I think they fixed it.

**Comment by Mixaz017** [comment]
Probably fixed, I dont get any reports about these anymore. Closing both
