### ISSUE TITLE
Extreme low FPS for mac.

### ISSUE THREAD

**Issue by FAKELF-DEV** [Mixaz017/idkr#8]

**Comment by Mixaz017** [comment]
Please provide further information.

**Comment by 0x506978656c** [comment]
Were looking for things like:

- what is your hardware specs
- is it only low fps
- are any other things such as resource loading witch is slow 
- are u using any external third party scripts or apps with the client 

Hope this helps clarify what we're looking for

**Comment by 0x506978656c** [comment]
@FAKELF-DEV any comments??? or should we close this issue?

**Comment by Mixaz017** [comment]
I have other cases of this, with decent specs but also with very high resolution monitor, and a dual monitor setup, not sure if I should close this

**Comment by ColdMoonNight** [comment]
@FAKELF-DEV if you still need help, it might be with you krunker settings being insanely high or sub-par specs. Try contacting Mixaz or Me on discord for some help if you don't check github

**Comment by mOdseenn** [comment]
i think its his macs problem bc i have an old mac, and no cap 120 frames on this with low settings and if i rlly go in i get 200
![Screen Shot 2021-03-26 at 4 49 56 PM](https://user-images.githubusercontent.com/81425796/112641429-7158b200-8e53-11eb-9b5d-d17f35cb16a2.png)

**Comment by KraXen72** [comment]
old mac with 120fps? what do you mean low fps? macs can't run shit, 120fps is a miracle, get a better computer + macs are not officially supported by the developer of this client (see readme). close this issue.

**Comment by Mixaz017** [comment]
> (see readme)

*sees readme*

> ## Supported Platforms
> | Platform | File Type |
> |-|-|
> | Windows | `exe` |
> | macOS | `dmg` |
> | Linux | `AppImage` |

???

**Comment by KraXen72** [comment]
my bad pretty sure i saw a 'not officially supported' disclaimer somewhere, but i guess that was a few versions ago... sorry, still, this issue does not make sense, since it won't run better than 120fps on an old mac. i tested it on an older mac (not old) and it ran like 30 fps, so 120 is not bad

**Comment by Zykkl** [comment]
Closed due to inactivity and no further information
